(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["styles"],{

/***/ "./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src/index.js?!./src/styles.css":
/*!*****************************************************************************************************************************************************************!*\
  !*** ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/styles.css ***!
  \*****************************************************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = [[module.i, "/* You can add global styles to this file, and also import other style files */\n@charset \"UTF-8\";\n/*\n\nStyle   : MobApp CSS\nVersion : 1.0\nAuthor  : Surjith S M\nURI     : https://surjithctly.in/\n\nCopyright © All rights Reserved \n\n*/\n/*------------------------\n[TABLE OF CONTENTS]\n    \n1. GLOBAL STYLES\n2. NAVBAR\n3. HERO\n4. TABS\n5. TESTIMONIALS\n6. IMAGE GALLERY\n7. PRICING\n8. CALL TO ACTION\n9. FOOTER\n\n/* #### Generated By: http://www.cufonfonts.com #### */\n@font-face {\n  font-family: 'Neo Sans TR Regular';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans TR Regular'), url('/assets/fonts/NeoSans TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans TR Light Italic';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans TR Light Italic'), url('/assets/fonts/NeoSans Light Italic TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans TR Medium';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans TR Medium'), url('/assets/fonts/NeoSans Medium TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans TR Black';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans TR Black'), url('/assets/fonts/NeoSans Black  TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans TR Ultra Italic';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans TR Ultra Italic'), url('/assets/fonts/NeoSans UltraItalic TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans  TR Italic';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans  TR Italic'), url('/assets/fonts/NeoSans Italic TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans Light';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans Light'), url('/assets/fonts/neo-sans-light.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans  TR Medium Italic';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans  TR Medium Italic'), url('/assets/fonts/NeoSansMedium Italic TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans  TR Bold';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans  TR Bold'), url('/assets/fonts/NeoSans Bold TR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans  TR Ultra';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans  TR Ultra'), url('/assets/fonts/NeoSans UltraTR.woff') format('woff');\n  }\n@font-face {\n  font-family: 'Neo Sans  TR Black Italic';\n  font-style: normal;\n  font-weight: normal;\n  src: local('fonts/Neo Sans  TR Black Italic'), url('/assets/fonts/NeoSans Black Italic TR.woff') format('woff');\n  }\n/*------------------------*/\n/* ajustes pequenos */\n.ajuste-text-align-right{\n    text-align: right;\n  }\n.ajuste-text-align-center{\n    text-align: center;\n  }\n.font-weight-bold{\n    font-weight: bold;\n  }\n.btn-cliente{\n      opacity: 0.6;\n      background-color: #fff;\n      padding: 1px 10px !important; \n  }\n.btn-cliente-ativo{\n    opacity: 1;\n  }\n.btn-cliente:hover,\n  .btn-cliente:focus,\n  .btn-cliente:active {  \n      opacity: 1;\n      background-color: #fff !important;\n      padding: 1px 10px !important; \n  }\n.label-itens-tela{\n    color: #666666\n  }\n.padding-zero{\n    padding: 0 !important;\n  }\n/*ajustes tabela inicio*/\n.border-tabela{\n    border: 2px solid #d3d3d3;\n  }\n.table-striped>tbody>tr:nth-of-type(even) {\n    background-color: #f9f9f9 !important;\n}\n.table-striped>tbody>tr:nth-of-type(odd) {\n  background-color: #fff !important;\n}\n.ajuste-thead{\n  background-color: #e0e0e0;\n}\n.table>tbody>tr>td,\n  .table>tbody>tr>th,\n  .table>tfoot>tr>td,\n  .table>tfoot>tr>th,\n  .table>thead>tr>td,\n  .table>thead>tr>th{\n    border-top: none;\n  }\n.total-preço{\n    float: right;\n    font-weight: bold;\n    margin: 5px 0 30px 0;\n  }\n.total-preço-cor{\n    color: #5b2f90;\n  }\n.links-tabela{\n    color: #5b2f90;\n    text-decoration: underline;\n  }\n.btn-atualizar{\n    margin: 4px 0 0 0 !important;\n    background-color: #fff !important;\n  }\n/*ajustes tabela fim*/\n/*ajustes etapas inicio*/\n.inline-block{display: inline-block;}\n.padding-left{padding: 0 0 0 20px;}\n.padding-right{padding: 0 20px 0 0;}\n.padding-left-right{padding: 0 20px 0 20px;}\n.ajuste-cesta-de-produtos{\n    margin-bottom: 30px;\n  }\n/*cesta de produtos*/\n.cesta-de-produtos-forms{\n    max-width: 160px;\n    font-size: 13px;\n    margin-right: 7px;\n  }\n.cesta-de-produtos-forms2{\n    max-width: 260px;\n    font-size: 13px;\n    margin-right: 7px;\n  }\n.ajuste-text-align-center{\n    text-align: center;\n  }\n.ajuste-barra-etapa-span{\n    display: inline-block;\n    background-color: #f7f8f8;\n    color: #7c7c7c;\n  }\n.ajuste-barra-etapa-span-selected{\n    background-color: #f7f8f8;\n    color: #421c5a;\n  }\n.ajuste-barra-etapas{\n    background: #c4c4c4;\n    height: 2px;\n    top: -10px;\n  }\n.ajuste-barra-itens{\n    z-index: 10;\n  }\n.etapas-numeros{\n    border: 1px solid grey;\n    border-radius: 50px;\n    display: inline-block;\n    text-align: center;\n    padding: 0px 6px;\n    color: #7c7c7c;\n}\n.etapas-numeros-selected{\n  background-color: #421c5a;\n  border: 1px solid #421c5a;\n  border-radius: 50px;\n  display: inline-block;\n  text-align: center;\n  padding: 0px 6px;\n  color: #fff;\n}\n/*ajustes etapas fim*/\n.btn-seta-left{\n  left:60px;\n}\n.btn-seta-right{\n  left: 0;\n}\n/* form */\n.form-control{\n  width: 100% !important;\n  height: 35px;\n  border-radius: 2px;\n  \n\n}\n/*form cliente e tipo de pedido*/\n.cliente-tipo{\n  float: right;\n}\n/*input inicio*/\n.exemplo1 input[type=radio], .exemplo1 input[type=checkbox], .exemplo2 input[type=checkbox]{\n  display:none; /* Esconde os inputs */\n}\n/*ajuste na tabela*/\n.ajuste-checkbox1{\n  top: 15px;\n  position: absolute;\n}\n/*Queries tamanho*/\n@media (max-width: 1289px) {\n  .ajuste-checkbox1{ \n   position:relative!important;\n   top: 10px;\n   border: none;\n   }\n  \n }\n@media (max-width: 899px) {\n .ajuste-checkbox1{ \n  position:relative!important;\n  top: 6px;\n  border: none;\n  }\n \n}\n@media (max-width: 899px) {\n  .ajuste-checkbox1{ \n   position:relative!important;\n   top: 6px;\n   border: none;\n   }\n  \n }\n.exemplo2{\n  top: 10px;\n  position: absolute;\n}\n.ajuste-row-checkbox{\n  width: 36px;\n}\n.exemplo1 input[type=radio] + label,\n.exemplo1 input[type=checkbox] + label,\n.exemplo2 input[type=checkbox] + label{\n  display:inline-block;\n  height:20px;\n  padding:0 0 0 25px;\n  margin:0 10px 0 0;\n  background-image: url(/assets/images/ico-master.png);\n  background-repeat:no-repeat;\n  background-position:0 0;\n  display: inline-block;\n  font-size: 13px;\n  color: #666666;\n  line-height: 21px;\n}\n.exemplo1 input[type=checkbox] + label,\n.exemplo2 input[type=checkbox] + label{\n  background-position:0 -60px; /* Muda a posição do background só no checkbox */\n}\n.exemplo1 input[type=checkbox]:checked + label {\n  background-position:0 -90px;\n}\n.exemplo2 input[type=checkbox]:checked + label {\n  background-position:0 -90px;\n}\n.exemplo2 input[type=checkbox]:checked + label {\n  background-position:0 -119px; /* sinal de menos */\n}\n.exemplo1 input[type=radio]:checked + label{\n  background-position:0 -30px;\n}\n/*ajuste na tabela*/\n.exemplo1, .exemplo2{\n  \n}\n/*input fim*/\n/* GLOBAL\n----------------------*/\nh2{\n  font-size: 18px;\n  /*font-family: Neo Sans TR Regular;*/\n  margin-bottom: 22px;\n  color: #4e4e4e;\n}\n.nav-label{\n  font-family:Neo Sans TR Regular;\n  display: inline-block;\n  width: 112px;\n  font-size: 13px;\n  margin-left: 8px;\n}\n.menu-pedido-de-venda{padding: 0 !important;}\n.menu-pedido-de-venda .nav-label{margin-left: 49px; }\n.menu-pedido-de-venda-display{\n  display: none !important;\n}\n.navbar-global {\n    background-color: indigo;\n  }\n.navbar-global .navbar-brand {\n    color: white;\n  }\n.navbar-global .navbar-user > li > a\n  {\n    color: white;\n  }\n.navbar-primary {\n    background-color: #fff;\n    bottom: 0px;\n    left: 0px;\n    position: absolute;\n    /*top: 51px;*/\n    top: 0;\n    width: 200px;\n    height: -webkit-max-content;\n    height: -moz-max-content;\n    height: max-content;\n    z-index: 8;\n    overflow: hidden;\n    transition: all 0.1s ease-in-out;\n    /*-webkit-box-shadow: 2px 2px 7px 0px rgba(222,222,222,0.25);\n    -moz-box-shadow: 2px 2px 7px 0px rgba(222,222,222,0.25);\n    box-shadow: 2px 2px 7px 0px rgba(222,222,222,0.25);*/\n  }\n.navbar-primary.collapsed {\n    width: 100px;\n  }\n.navbar-primary.collapsed .glyphicon {\n    font-size: 17px;\n  }\n.navbar-primary.collapsed .nav-label {\n    display: none;\n  }\n.btn-expand-collapse {\n      outline: none;\n      margin-bottom: 29px;\n      /*position: absolute;*/\n      display: block;\n      left: 0px;\n      bottom:0;\n      width: 100%;\n      padding: 21px 0;\n      border-bottom: 1px solid #dbdbdb;  \n      /*border-top:solid 1px #666;*/\n      color: #ccc;\n      font-size: 20px;\n      text-align: center;\n      border-top: 0;\n      border-left: 0;\n      border-right: 0;\n      background-color: #fff;\n      webkit-box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.05);\n    box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.05);\n  }\n.btn-expand-collapse:hover,\n  .btn-expand-collapse:focus {\n      background-color: #fff;\n      color: #ccc;\n  }\n.btn-expand-collapse:active {\n      background-color: #fff;\n  }\n.navbar-primary-menu,\n  .navbar-primary-menu li {\n    margin:0; padding:0;\n    list-style: none;\n  }\n.navbar-primary-menu li a {\n    display: block;\n    padding: 10px 18px;\n    text-align: left;\n    /*border-bottom:solid 1px #444;*/\n    color: #94979b;\n  }\n.navbar-primary-menu li a:hover {\n    color: #5c2e90;\n    background-color: #fff;\n    text-decoration: none;\n  }\n.navbar-primary-menu li a:active,\n  .navbar-primary-menu li a:focus{\n    color: #5c2e90;\n    text-decoration: none;\n  }\n.navbar-primary-menu li a .glyphicon {\n    display: inline-block;\n    color: #94979b;\n    margin-right: 6px;\n    font-size: 17px;\n  }\n.ajuste-navbar-primary-icons{\n    top: -6px;\n  }\n.navbar-primary-menu li a:hover .glyphicon {\n    color: #5c2e90;\n  }\n.navbar-primary-menu li a:focus .glyphicon {\n    color: #5c2e90;\n  }\n.main-content {\n    overflow-x: hidden;\n    background-color: #f7f8f8;\n    /*margin-top: 60px;*/\n    margin-left: 200px;\n    padding: 0 0 90px 0;\n    box-shadow: inset 10px 0px 7px -7px rgba(222,222,222,0.25);\n  }\n.main-content2{\n    overflow-x: hidden;\n    background-color: #f7f8f8;\n    /*margin-top: 60px;*/\n    margin-left: 100px;\n    padding: 0 0 90px 0;\n    box-shadow: inset 10px 0px 7px -7px rgba(222,222,222,0.25);\n   }\n.main-content h1{\n    font-size: 18px;\n    margin: 0;\n    padding: 27px 0 24px 30px;\n    border-bottom: 1px solid #dbdbdb;\n  }\n.collapsed + .main-content {\n    margin-left: 100px;\n    padding: 0 0 60px 0;\n  }\n.collapsed .navbar-primary-menu li a {\n    text-align: center;\n  }\n.collapsed .logo {display:none;}\n.logo {\n    display: inline-block;\n    position: absolute;\n    left: 22px;\n    top: 16px;\n  }\n/*botoes-iniciais*/\n.botoes-iniciais{\n    border-bottom: 1px solid #dbdbdb;\n    padding: 0 30px;\n  }\n.btn-inicio{\n    margin: 10px 0 10px 0;\n    border-radius: 2px;\n    font-size: 13px;\n    font-weight: bold;\n  }\n.btn-topo-direita{\n    background-color: #f7f8f8;\n    color: #666;\n  }\n.btn-topo-direita:hover,\n  .btn-topo-direita:active,\n  .btn-topo-direita:focus\n\n  {\n    color: #fff !important;\n    background-color: #421b5b !important;\n    border-color: #421b5b !important;\n  }\n.btn-proximo{\n    background-color: #421b5b;\n    color: #fff;\n    border: 1px solid #421b5b;\n    margin-left: 10px;\n  }\n.btn-proximo:hover,\n  .btn-proximo:active,\n  .btn-proximo:focus{\n    color: #fff !important;\n    background-color: #341857 !important;\n    border: 1px solid #341857 !important;\n  }\n.btn-pause{\n    border: 1px solid #421b5b;\n    color: #421b5b;\n    background-color: #f7f8f8;\n    margin-right: 10px;\n  }\n.btn-pause:hover,\n  .btn-pause:active,\n  .btn-pause:focus{\n    color: #fff !important;\n    background-color: #421b5b !important;\n    border: 1px solid #421b5b !important;\n  }\n.block-branco-ajuste-altura1{\n    margin: 28px 28px 0 28px !important;\n  }\n.block-branco-ajuste-altura2{\n    margin: 0 28px 28px 28px  !important;\n  }\n.block-branco{\n    margin: 28px 28px;\n    padding: 0 10px 0 10px;\n    background: #fff;\n    border-radius: 4px;\n   box-shadow: 0px 0px 2px 1px rgba(0,0,0,0.09);\n  }\n.block-branco-search{\n    padding: 20px 20px 20px 15px;\n    background: #fff;\n    border-radius: 1px;\n    box-shadow: 10px 10px 19px -12px rgba(0,0,0,0.6);\n    border: 1px solid #ccc;\n    position: absolute;\n    z-index: 99999;\n    width: 97%;\n    left: 31px;\n    top: 34px;\n  }\n.block-branco-flymenu{\n    padding: 20px 18px 20px 12px;\n    background: #fff;\n    border-radius: 1px;\n    box-shadow: 10px 10px 19px -12px rgba(0,0,0,0.6);\n    border: 1px solid #ccc;\n    position: absolute;\n    z-index: 99999;\n    width: 97%;\n    left: 31px;\n    top: 34px;\n  }\n.bloco-normal{\n    margin: 28px 28px;\n  }\n.block-cinza{\n    padding: 21px 18px 5px 8px;\n    background: #f4f4f4;\n    border-radius: 4px;\n    border-right: 40px solid #e0e0e0;\n    margin: 0px 0px 22px 0;\n    box-shadow: 2px 2px 0px 0px rgba(222,222,222,1);\n    position: relative;\n  }\n.block-cinza-search{\n    padding: 20px 18px 20px 5px;\n    background: #f4f4f4;\n    border-radius: 6px;\n    margin: 0 0 20px 4px;\n    border: 1px solid rgb(224, 224, 224);\n    position: relative;\n  }\n.search-produto-text{\n    color: #7c7c7c;\n  }\n.search-image{    \n    border-radius: 4px;\n    border: 1px solid #c2c2c2;\n    min-width: 90px;\n  }\n.btn-produto-adicionar{\n    border: 1px solid #5b2f90;\n    color: #5b2f90;\n    background-color: #f4f4f4;\n  }\n.btn-produto-adicionar:hover, .btn-produto-adicionar:active, .btn-produto-adicionarn-pause:focus {\n    color: #fff !important;\n    background-color: #471f79 !important;\n    border: 1px solid #471f79 !important;\n}\n.btn-ver-tudo-search{\n    text-align: center;\n    /* display: block; */\n    /* width: 14%; */\n    background-color: #fff;\n  }\n.campo-busca{\n  \n}\n.icone-campo-busca{\n    background-repeat: no-repeat;\n    display: inline-block;\n    background-image: url(/assets/images/ico-master.png);\n    background-position: 0 -139px;\n    float: right;\n    width: 30px;\n    height: 30px;\n    margin: -32px 0 0 0;\n}\n.table-form-quantidade{\n  padding: 6px 5px !important;\n  max-width: 33px;\n  display: inline-block;\n}\n/*descomentar*/\n.search_box{\n  display:none;\n}\n.adicionar-junto{\n  display:none;\n}\n.active-search{\n  display: block;\n}\n.active-adicionar-junto{\n  display:block !important;\n}\n/* DRAGGABLE */\n#draggable{\n  padding-top: 0 !important;\n  max-width: 560px;\n  min-height: 150px;\n  position: absolute;\n  z-index:999999;\n  border-radius: 6px;\n  box-shadow: 10px 10px 19px -12px rgba(0,0,0,0.6);\n  border: 1px solid #adadad;\n}\n.adicionar-junto-title{\n  background-color: #421b5b;\n    margin-bottom: 20px;\n    color: #fff;\n    padding: 20px 20px;\n    font-size: 18px;\n    top: -1px;\n    left: 3px;\n    border-top-left-radius: 6px;\n    border-top-right-radius: 6px;\n    max-width: 560px;\n}\n/* SCROLL BAR CSS*/\n::-webkit-scrollbar-track {\n  background-color: rgb(145, 145, 145);\n}\n::-webkit-scrollbar {\n  width: 12px;\n  background: rgb(58, 58, 58);\n}\n::-webkit-scrollbar-thumb {\n  background: #5c5c5c;\n  /*border-radius: 8px;*/\n}\n/*css tabela*/\n.table>tbody>tr>td,\n.table>tbody>tr>th,\n.table>tfoot>tr>td,\n.table>tfoot>tr>th,\n.table>thead>tr>td,\n.table>thead>tr>th{\n      padding: 8px 10px;\n      line-height: 1.42857143;\n      vertical-align: initial;\n      /*border-top: 1px solid #ddd;*/\n      font-size: 12px;\n      position: relative;\n}\n.table>thead:first-child>tr:first-child>th{\n  padding: 12px 10px;\n}\n.btn-mais{\n  background-repeat: no-repeat;\n  display: inline-block;\n  background-image: url(/assets/images/ico-master.png);\n  background-position: 0 -192px;\n  width: 19px;\n  height: 22px;\n}\n.btn-menos{\n  background-repeat: no-repeat;\n  display: inline-block;\n  background-image: url(/assets/images/ico-master.png);\n  background-position: 0 -170px;\n  width: 19px;\n  height: 22px;\n}\n/*Queries tamanho*/\n@media (max-width: 991px) {\n  .ajuste-barra-etapas{display: none;}\n  .ajuste-barra-itens{text-align: left;}\n  .ajuste-barra-etapa-span{padding: 10px 0 10px 0 !important;}\n  .ajuste-mobile-esquerda{text-align:left;}\n}\n@media (max-width: 808px) {\n  .icone-campo-busca{background-image: none;}\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZXMuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLDhFQUE4RTtBQUM5RSxnQkFBZ0I7QUFFaEI7Ozs7Ozs7OztDQVNDO0FBR0Q7Ozs7Ozs7Ozs7Ozs7c0RBYXNEO0FBRXREO0VBQ0Usa0NBQWtDO0VBQ2xDLGtCQUFrQjtFQUNsQixtQkFBbUI7RUFDbkIsNEZBQTRGO0VBQzVGO0FBR0E7RUFDQSx1Q0FBdUM7RUFDdkMsa0JBQWtCO0VBQ2xCLG1CQUFtQjtFQUNuQiw4R0FBOEc7RUFDOUc7QUFHQTtFQUNBLGlDQUFpQztFQUNqQyxrQkFBa0I7RUFDbEIsbUJBQW1CO0VBQ25CLGtHQUFrRztFQUNsRztBQUdBO0VBQ0EsZ0NBQWdDO0VBQ2hDLGtCQUFrQjtFQUNsQixtQkFBbUI7RUFDbkIsaUdBQWlHO0VBQ2pHO0FBR0E7RUFDQSx1Q0FBdUM7RUFDdkMsa0JBQWtCO0VBQ2xCLG1CQUFtQjtFQUNuQiw2R0FBNkc7RUFDN0c7QUFHQTtFQUNBLGtDQUFrQztFQUNsQyxrQkFBa0I7RUFDbEIsbUJBQW1CO0VBQ25CLG1HQUFtRztFQUNuRztBQUdBO0VBQ0EsNkJBQTZCO0VBQzdCLGtCQUFrQjtFQUNsQixtQkFBbUI7RUFDbkIsMkZBQTJGO0VBQzNGO0FBR0E7RUFDQSx5Q0FBeUM7RUFDekMsa0JBQWtCO0VBQ2xCLG1CQUFtQjtFQUNuQixnSEFBZ0g7RUFDaEg7QUFHQTtFQUNBLGdDQUFnQztFQUNoQyxrQkFBa0I7RUFDbEIsbUJBQW1CO0VBQ25CLCtGQUErRjtFQUMvRjtBQUdBO0VBQ0EsaUNBQWlDO0VBQ2pDLGtCQUFrQjtFQUNsQixtQkFBbUI7RUFDbkIsZ0dBQWdHO0VBQ2hHO0FBR0E7RUFDQSx3Q0FBd0M7RUFDeEMsa0JBQWtCO0VBQ2xCLG1CQUFtQjtFQUNuQiwrR0FBK0c7RUFDL0c7QUFJQSwyQkFBMkI7QUFFM0IscUJBQXFCO0FBQ3JCO0lBQ0UsaUJBQWlCO0VBQ25CO0FBQ0E7SUFDRSxrQkFBa0I7RUFDcEI7QUFFQTtJQUNFLGlCQUFpQjtFQUNuQjtBQUNBO01BQ0ksWUFBWTtNQUNaLHNCQUFzQjtNQUN0Qiw0QkFBNEI7RUFDaEM7QUFFQTtJQUNFLFVBQVU7RUFDWjtBQUVBOzs7TUFHSSxVQUFVO01BQ1YsaUNBQWlDO01BQ2pDLDRCQUE0QjtFQUNoQztBQUVBO0lBQ0U7RUFDRjtBQUVBO0lBQ0UscUJBQXFCO0VBQ3ZCO0FBR0Esd0JBQXdCO0FBQ3hCO0lBQ0UseUJBQXlCO0VBQzNCO0FBRUE7SUFDRSxvQ0FBb0M7QUFDeEM7QUFFQTtFQUNFLGlDQUFpQztBQUNuQztBQUVBO0VBQ0UseUJBQXlCO0FBQzNCO0FBRUU7Ozs7OztJQU1FLGdCQUFnQjtFQUNsQjtBQUVBO0lBQ0UsWUFBWTtJQUNaLGlCQUFpQjtJQUNqQixvQkFBb0I7RUFDdEI7QUFDQTtJQUNFLGNBQWM7RUFDaEI7QUFFQTtJQUNFLGNBQWM7SUFDZCwwQkFBMEI7RUFDNUI7QUFFQTtJQUNFLDRCQUE0QjtJQUM1QixpQ0FBaUM7RUFDbkM7QUFFRCxxQkFBcUI7QUFLdEIsd0JBQXdCO0FBQ3RCLGNBQWMscUJBQXFCLENBQUM7QUFDcEMsY0FBYyxtQkFBbUIsQ0FBQztBQUNsQyxlQUFlLG1CQUFtQixDQUFDO0FBQ25DLG9CQUFvQixzQkFBc0IsQ0FBQztBQUUzQztJQUNFLG1CQUFtQjtFQUNyQjtBQUVBLG9CQUFvQjtBQUNwQjtJQUNFLGdCQUFnQjtJQUNoQixlQUFlO0lBQ2YsaUJBQWlCO0VBQ25CO0FBRUE7SUFDRSxnQkFBZ0I7SUFDaEIsZUFBZTtJQUNmLGlCQUFpQjtFQUNuQjtBQUdBO0lBQ0Usa0JBQWtCO0VBQ3BCO0FBRUE7SUFDRSxxQkFBcUI7SUFDckIseUJBQXlCO0lBQ3pCLGNBQWM7RUFDaEI7QUFFQTtJQUNFLHlCQUF5QjtJQUN6QixjQUFjO0VBQ2hCO0FBRUE7SUFDRSxtQkFBbUI7SUFDbkIsV0FBVztJQUNYLFVBQVU7RUFDWjtBQUVBO0lBQ0UsV0FBVztFQUNiO0FBRUE7SUFDRSxzQkFBc0I7SUFDdEIsbUJBQW1CO0lBQ25CLHFCQUFxQjtJQUNyQixrQkFBa0I7SUFDbEIsZ0JBQWdCO0lBQ2hCLGNBQWM7QUFDbEI7QUFFQTtFQUNFLHlCQUF5QjtFQUN6Qix5QkFBeUI7RUFDekIsbUJBQW1CO0VBQ25CLHFCQUFxQjtFQUNyQixrQkFBa0I7RUFDbEIsZ0JBQWdCO0VBQ2hCLFdBQVc7QUFDYjtBQUdBLHFCQUFxQjtBQUlyQjtFQUNFLFNBQVM7QUFDWDtBQUNBO0VBQ0UsT0FBTztBQUNUO0FBRUEsU0FBUztBQUNUO0VBQ0Usc0JBQXNCO0VBQ3RCLFlBQVk7RUFDWixrQkFBa0I7OztBQUdwQjtBQUVBLGdDQUFnQztBQUNoQztFQUNFLFlBQVk7QUFDZDtBQUdBLGVBQWU7QUFDZjtFQUNFLFlBQVksRUFBRSxzQkFBc0I7QUFDdEM7QUFFQSxtQkFBbUI7QUFDbkI7RUFDRSxTQUFTO0VBQ1Qsa0JBQWtCO0FBQ3BCO0FBRUEsa0JBQWtCO0FBQ2xCO0VBQ0U7R0FDQywyQkFBMkI7R0FDM0IsU0FBUztHQUNULFlBQVk7R0FDWjs7Q0FFRjtBQUVEO0NBQ0M7RUFDQywyQkFBMkI7RUFDM0IsUUFBUTtFQUNSLFlBQVk7RUFDWjs7QUFFRjtBQUNBO0VBQ0U7R0FDQywyQkFBMkI7R0FDM0IsUUFBUTtHQUNSLFlBQVk7R0FDWjs7Q0FFRjtBQUlEO0VBQ0UsU0FBUztFQUNULGtCQUFrQjtBQUNwQjtBQUNBO0VBQ0UsV0FBVztBQUNiO0FBSUE7OztFQUdFLG9CQUFvQjtFQUNwQixXQUFXO0VBQ1gsa0JBQWtCO0VBQ2xCLGlCQUFpQjtFQUNqQixvREFBb0Q7RUFDcEQsMkJBQTJCO0VBQzNCLHVCQUF1QjtFQUN2QixxQkFBcUI7RUFDckIsZUFBZTtFQUNmLGNBQWM7RUFDZCxpQkFBaUI7QUFDbkI7QUFHQTs7RUFFRSwyQkFBMkIsRUFBRSxnREFBZ0Q7QUFDL0U7QUFFQTtFQUNFLDJCQUEyQjtBQUM3QjtBQUVBO0VBQ0UsMkJBQTJCO0FBQzdCO0FBRUE7RUFDRSw0QkFBNEIsRUFBRSxtQkFBbUI7QUFDbkQ7QUFFQTtFQUNFLDJCQUEyQjtBQUM3QjtBQUVBLG1CQUFtQjtBQUNuQjs7QUFFQTtBQUdBLFlBQVk7QUFHWjt1QkFDdUI7QUFFdkI7RUFDRSxlQUFlO0VBQ2Ysb0NBQW9DO0VBQ3BDLG1CQUFtQjtFQUNuQixjQUFjO0FBQ2hCO0FBRUE7RUFDRSwrQkFBK0I7RUFDL0IscUJBQXFCO0VBQ3JCLFlBQVk7RUFDWixlQUFlO0VBQ2YsZ0JBQWdCO0FBQ2xCO0FBRUEsc0JBQXNCLHFCQUFxQixDQUFDO0FBQzVDLGlDQUFpQyxpQkFBaUIsRUFBRTtBQUNwRDtFQUNFLHdCQUF3QjtBQUMxQjtBQUdBO0lBQ0ksd0JBQXdCO0VBQzFCO0FBRUE7SUFDRSxZQUFZO0VBQ2Q7QUFFQTs7SUFFRSxZQUFZO0VBQ2Q7QUFFQTtJQUNFLHNCQUFzQjtJQUN0QixXQUFXO0lBQ1gsU0FBUztJQUNULGtCQUFrQjtJQUNsQixhQUFhO0lBQ2IsTUFBTTtJQUNOLFlBQVk7SUFDWiwyQkFBbUI7SUFBbkIsd0JBQW1CO0lBQW5CLG1CQUFtQjtJQUNuQixVQUFVO0lBQ1YsZ0JBQWdCO0lBR2hCLGdDQUFnQztJQUNoQzs7d0RBRW9EO0VBQ3REO0FBRUE7SUFDRSxZQUFZO0VBQ2Q7QUFFQTtJQUNFLGVBQWU7RUFDakI7QUFFQTtJQUNFLGFBQWE7RUFDZjtBQUVBO01BQ0ksYUFBYTtNQUNiLG1CQUFtQjtNQUNuQixzQkFBc0I7TUFDdEIsY0FBYztNQUNkLFNBQVM7TUFDVCxRQUFRO01BQ1IsV0FBVztNQUNYLGVBQWU7TUFDZixnQ0FBZ0M7TUFDaEMsNkJBQTZCO01BQzdCLFdBQVc7TUFDWCxlQUFlO01BQ2Ysa0JBQWtCO01BQ2xCLGFBQWE7TUFDYixjQUFjO01BQ2QsZUFBZTtNQUNmLHNCQUFzQjtNQUN0QixtREFBbUQ7SUFFckQsNENBQTRDO0VBQzlDO0FBRUE7O01BRUksc0JBQXNCO01BQ3RCLFdBQVc7RUFDZjtBQUVBO01BQ0ksc0JBQXNCO0VBQzFCO0FBRUE7O0lBRUUsUUFBUSxFQUFFLFNBQVM7SUFDbkIsZ0JBQWdCO0VBQ2xCO0FBSUE7SUFDRSxjQUFjO0lBQ2Qsa0JBQWtCO0lBQ2xCLGdCQUFnQjtJQUNoQixnQ0FBZ0M7SUFDaEMsY0FBYztFQUNoQjtBQUVBO0lBQ0UsY0FBYztJQUNkLHNCQUFzQjtJQUN0QixxQkFBcUI7RUFDdkI7QUFFQTs7SUFFRSxjQUFjO0lBQ2QscUJBQXFCO0VBQ3ZCO0FBRUE7SUFDRSxxQkFBcUI7SUFDckIsY0FBYztJQUNkLGlCQUFpQjtJQUNqQixlQUFlO0VBQ2pCO0FBRUE7SUFDRSxTQUFTO0VBQ1g7QUFFQTtJQUNFLGNBQWM7RUFDaEI7QUFDQTtJQUNFLGNBQWM7RUFDaEI7QUFFQTtJQUNFLGtCQUFrQjtJQUNsQix5QkFBeUI7SUFDekIsb0JBQW9CO0lBQ3BCLGtCQUFrQjtJQUNsQixtQkFBbUI7SUFHbkIsMERBQTBEO0VBQzVEO0FBRUE7SUFDRSxrQkFBa0I7SUFDbEIseUJBQXlCO0lBQ3pCLG9CQUFvQjtJQUNwQixrQkFBa0I7SUFDbEIsbUJBQW1CO0lBR25CLDBEQUEwRDtHQUMzRDtBQUdEO0lBQ0UsZUFBZTtJQUNmLFNBQVM7SUFDVCx5QkFBeUI7SUFDekIsZ0NBQWdDO0VBQ2xDO0FBS0E7SUFDRSxrQkFBa0I7SUFDbEIsbUJBQW1CO0VBQ3JCO0FBRUE7SUFDRSxrQkFBa0I7RUFDcEI7QUFFQSxrQkFBa0IsWUFBWSxDQUFDO0FBRy9CO0lBQ0UscUJBQXFCO0lBQ3JCLGtCQUFrQjtJQUNsQixVQUFVO0lBQ1YsU0FBUztFQUNYO0FBRUEsa0JBQWtCO0FBQ2xCO0lBQ0UsZ0NBQWdDO0lBQ2hDLGVBQWU7RUFDakI7QUFFQTtJQUNFLHFCQUFxQjtJQUNyQixrQkFBa0I7SUFDbEIsZUFBZTtJQUNmLGlCQUFpQjtFQUNuQjtBQUVBO0lBQ0UseUJBQXlCO0lBQ3pCLFdBQVc7RUFDYjtBQUVBOzs7OztJQUtFLHNCQUFzQjtJQUN0QixvQ0FBb0M7SUFDcEMsZ0NBQWdDO0VBQ2xDO0FBRUE7SUFDRSx5QkFBeUI7SUFDekIsV0FBVztJQUNYLHlCQUF5QjtJQUN6QixpQkFBaUI7RUFDbkI7QUFFQTs7O0lBR0Usc0JBQXNCO0lBQ3RCLG9DQUFvQztJQUNwQyxvQ0FBb0M7RUFDdEM7QUFFQTtJQUNFLHlCQUF5QjtJQUN6QixjQUFjO0lBQ2QseUJBQXlCO0lBQ3pCLGtCQUFrQjtFQUNwQjtBQUVBOzs7SUFHRSxzQkFBc0I7SUFDdEIsb0NBQW9DO0lBQ3BDLG9DQUFvQztFQUN0QztBQUdBO0lBQ0UsbUNBQW1DO0VBQ3JDO0FBRUE7SUFDRSxvQ0FBb0M7RUFDdEM7QUFJQTtJQUNFLGlCQUFpQjtJQUNqQixzQkFBc0I7SUFDdEIsZ0JBQWdCO0lBQ2hCLGtCQUFrQjtHQUduQiw0Q0FBNEM7RUFDN0M7QUFFQTtJQUNFLDRCQUE0QjtJQUM1QixnQkFBZ0I7SUFDaEIsa0JBQWtCO0lBR2xCLGdEQUFnRDtJQUNoRCxzQkFBc0I7SUFDdEIsa0JBQWtCO0lBQ2xCLGNBQWM7SUFDZCxVQUFVO0lBQ1YsVUFBVTtJQUNWLFNBQVM7RUFDWDtBQUdBO0lBQ0UsNEJBQTRCO0lBQzVCLGdCQUFnQjtJQUNoQixrQkFBa0I7SUFHbEIsZ0RBQWdEO0lBQ2hELHNCQUFzQjtJQUN0QixrQkFBa0I7SUFDbEIsY0FBYztJQUNkLFVBQVU7SUFDVixVQUFVO0lBQ1YsU0FBUztFQUNYO0FBR0E7SUFDRSxpQkFBaUI7RUFDbkI7QUFFQTtJQUNFLDBCQUEwQjtJQUMxQixtQkFBbUI7SUFDbkIsa0JBQWtCO0lBQ2xCLGdDQUFnQztJQUNoQyxzQkFBc0I7SUFHdEIsK0NBQStDO0lBQy9DLGtCQUFrQjtFQUNwQjtBQUVBO0lBQ0UsMkJBQTJCO0lBQzNCLG1CQUFtQjtJQUNuQixrQkFBa0I7SUFDbEIsb0JBQW9CO0lBQ3BCLG9DQUFvQztJQUNwQyxrQkFBa0I7RUFDcEI7QUFFQTtJQUNFLGNBQWM7RUFDaEI7QUFFQTtJQUNFLGtCQUFrQjtJQUNsQix5QkFBeUI7SUFDekIsZUFBZTtFQUNqQjtBQUVBO0lBQ0UseUJBQXlCO0lBQ3pCLGNBQWM7SUFDZCx5QkFBeUI7RUFDM0I7QUFDQTtJQUNFLHNCQUFzQjtJQUN0QixvQ0FBb0M7SUFDcEMsb0NBQW9DO0FBQ3hDO0FBRUU7SUFDRSxrQkFBa0I7SUFDbEIsb0JBQW9CO0lBQ3BCLGdCQUFnQjtJQUNoQixzQkFBc0I7RUFDeEI7QUFFRjs7QUFFQTtBQUVBO0lBQ0ksNEJBQTRCO0lBQzVCLHFCQUFxQjtJQUNyQixvREFBb0Q7SUFDcEQsNkJBQTZCO0lBQzdCLFlBQVk7SUFDWixXQUFXO0lBQ1gsWUFBWTtJQUNaLG1CQUFtQjtBQUN2QjtBQUVBO0VBQ0UsMkJBQTJCO0VBQzNCLGVBQWU7RUFDZixxQkFBcUI7QUFDdkI7QUFFQSxjQUFjO0FBQ2Q7RUFDRSxZQUFZO0FBQ2Q7QUFDQTtFQUNFLFlBQVk7QUFDZDtBQUVBO0VBQ0UsY0FBYztBQUNoQjtBQUNBO0VBQ0Usd0JBQXdCO0FBQzFCO0FBSUEsY0FBYztBQUNkO0VBQ0UseUJBQXlCO0VBQ3pCLGdCQUFnQjtFQUNoQixpQkFBaUI7RUFDakIsa0JBQWtCO0VBQ2xCLGNBQWM7RUFDZCxrQkFBa0I7RUFHbEIsZ0RBQWdEO0VBQ2hELHlCQUF5QjtBQUMzQjtBQUVBO0VBQ0UseUJBQXlCO0lBQ3ZCLG1CQUFtQjtJQUNuQixXQUFXO0lBQ1gsa0JBQWtCO0lBQ2xCLGVBQWU7SUFDZixTQUFTO0lBQ1QsU0FBUztJQUNULDJCQUEyQjtJQUMzQiw0QkFBNEI7SUFDNUIsZ0JBQWdCO0FBQ3BCO0FBR0Esa0JBQWtCO0FBRWxCO0VBQ0Usb0NBQW9DO0FBQ3RDO0FBQ0E7RUFDRSxXQUFXO0VBQ1gsMkJBQTJCO0FBQzdCO0FBQ0E7RUFDRSxtQkFBbUI7RUFDbkIsc0JBQXNCO0FBQ3hCO0FBRUEsYUFBYTtBQUNiOzs7Ozs7TUFNTSxpQkFBaUI7TUFDakIsdUJBQXVCO01BQ3ZCLHVCQUF1QjtNQUN2Qiw4QkFBOEI7TUFDOUIsZUFBZTtNQUNmLGtCQUFrQjtBQUN4QjtBQUVBO0VBQ0Usa0JBQWtCO0FBQ3BCO0FBRUE7RUFDRSw0QkFBNEI7RUFDNUIscUJBQXFCO0VBQ3JCLG9EQUFvRDtFQUNwRCw2QkFBNkI7RUFDN0IsV0FBVztFQUNYLFlBQVk7QUFDZDtBQUVBO0VBQ0UsNEJBQTRCO0VBQzVCLHFCQUFxQjtFQUNyQixvREFBb0Q7RUFDcEQsNkJBQTZCO0VBQzdCLFdBQVc7RUFDWCxZQUFZO0FBQ2Q7QUFFQSxrQkFBa0I7QUFDbEI7RUFDRSxxQkFBcUIsYUFBYSxDQUFDO0VBQ25DLG9CQUFvQixnQkFBZ0IsQ0FBQztFQUNyQyx5QkFBeUIsaUNBQWlDLENBQUM7RUFDM0Qsd0JBQXdCLGVBQWUsQ0FBQztBQUMxQztBQUVBO0VBQ0UsbUJBQW1CLHNCQUFzQixDQUFDO0FBQzVDIiwiZmlsZSI6InNyYy9zdHlsZXMuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLyogWW91IGNhbiBhZGQgZ2xvYmFsIHN0eWxlcyB0byB0aGlzIGZpbGUsIGFuZCBhbHNvIGltcG9ydCBvdGhlciBzdHlsZSBmaWxlcyAqL1xuQGNoYXJzZXQgXCJVVEYtOFwiO1xuXG4vKlxuXG5TdHlsZSAgIDogTW9iQXBwIENTU1xuVmVyc2lvbiA6IDEuMFxuQXV0aG9yICA6IFN1cmppdGggUyBNXG5VUkkgICAgIDogaHR0cHM6Ly9zdXJqaXRoY3RseS5pbi9cblxuQ29weXJpZ2h0IMKpIEFsbCByaWdodHMgUmVzZXJ2ZWQgXG5cbiovXG5cblxuLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbltUQUJMRSBPRiBDT05URU5UU11cbiAgICBcbjEuIEdMT0JBTCBTVFlMRVNcbjIuIE5BVkJBUlxuMy4gSEVST1xuNC4gVEFCU1xuNS4gVEVTVElNT05JQUxTXG42LiBJTUFHRSBHQUxMRVJZXG43LiBQUklDSU5HXG44LiBDQUxMIFRPIEFDVElPTlxuOS4gRk9PVEVSXG5cbi8qICMjIyMgR2VuZXJhdGVkIEJ5OiBodHRwOi8vd3d3LmN1Zm9uZm9udHMuY29tICMjIyMgKi9cblxuQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgVFIgUmVndWxhcic7XG4gIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgZm9udC13ZWlnaHQ6IG5vcm1hbDtcbiAgc3JjOiBsb2NhbCgnZm9udHMvTmVvIFNhbnMgVFIgUmVndWxhcicpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBUUi53b2ZmJykgZm9ybWF0KCd3b2ZmJyk7XG4gIH1cbiAgXG4gIFxuICBAZm9udC1mYWNlIHtcbiAgZm9udC1mYW1pbHk6ICdOZW8gU2FucyBUUiBMaWdodCBJdGFsaWMnO1xuICBmb250LXN0eWxlOiBub3JtYWw7XG4gIGZvbnQtd2VpZ2h0OiBub3JtYWw7XG4gIHNyYzogbG9jYWwoJ2ZvbnRzL05lbyBTYW5zIFRSIExpZ2h0IEl0YWxpYycpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBMaWdodCBJdGFsaWMgVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG4gIFxuICBcbiAgQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgVFIgTWVkaXVtJztcbiAgZm9udC1zdHlsZTogbm9ybWFsO1xuICBmb250LXdlaWdodDogbm9ybWFsO1xuICBzcmM6IGxvY2FsKCdmb250cy9OZW8gU2FucyBUUiBNZWRpdW0nKSwgdXJsKCcvYXNzZXRzL2ZvbnRzL05lb1NhbnMgTWVkaXVtIFRSLndvZmYnKSBmb3JtYXQoJ3dvZmYnKTtcbiAgfVxuICBcbiAgXG4gIEBmb250LWZhY2Uge1xuICBmb250LWZhbWlseTogJ05lbyBTYW5zIFRSIEJsYWNrJztcbiAgZm9udC1zdHlsZTogbm9ybWFsO1xuICBmb250LXdlaWdodDogbm9ybWFsO1xuICBzcmM6IGxvY2FsKCdmb250cy9OZW8gU2FucyBUUiBCbGFjaycpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBCbGFjayAgVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG4gIFxuICBcbiAgQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgVFIgVWx0cmEgSXRhbGljJztcbiAgZm9udC1zdHlsZTogbm9ybWFsO1xuICBmb250LXdlaWdodDogbm9ybWFsO1xuICBzcmM6IGxvY2FsKCdmb250cy9OZW8gU2FucyBUUiBVbHRyYSBJdGFsaWMnKSwgdXJsKCcvYXNzZXRzL2ZvbnRzL05lb1NhbnMgVWx0cmFJdGFsaWMgVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG4gIFxuICBcbiAgQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgIFRSIEl0YWxpYyc7XG4gIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgZm9udC13ZWlnaHQ6IG5vcm1hbDtcbiAgc3JjOiBsb2NhbCgnZm9udHMvTmVvIFNhbnMgIFRSIEl0YWxpYycpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBJdGFsaWMgVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG4gIFxuICBcbiAgQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgTGlnaHQnO1xuICBmb250LXN0eWxlOiBub3JtYWw7XG4gIGZvbnQtd2VpZ2h0OiBub3JtYWw7XG4gIHNyYzogbG9jYWwoJ2ZvbnRzL05lbyBTYW5zIExpZ2h0JyksIHVybCgnL2Fzc2V0cy9mb250cy9uZW8tc2Fucy1saWdodC53b2ZmJykgZm9ybWF0KCd3b2ZmJyk7XG4gIH1cbiAgXG4gIFxuICBAZm9udC1mYWNlIHtcbiAgZm9udC1mYW1pbHk6ICdOZW8gU2FucyAgVFIgTWVkaXVtIEl0YWxpYyc7XG4gIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgZm9udC13ZWlnaHQ6IG5vcm1hbDtcbiAgc3JjOiBsb2NhbCgnZm9udHMvTmVvIFNhbnMgIFRSIE1lZGl1bSBJdGFsaWMnKSwgdXJsKCcvYXNzZXRzL2ZvbnRzL05lb1NhbnNNZWRpdW0gSXRhbGljIFRSLndvZmYnKSBmb3JtYXQoJ3dvZmYnKTtcbiAgfVxuICBcbiAgXG4gIEBmb250LWZhY2Uge1xuICBmb250LWZhbWlseTogJ05lbyBTYW5zICBUUiBCb2xkJztcbiAgZm9udC1zdHlsZTogbm9ybWFsO1xuICBmb250LXdlaWdodDogbm9ybWFsO1xuICBzcmM6IGxvY2FsKCdmb250cy9OZW8gU2FucyAgVFIgQm9sZCcpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBCb2xkIFRSLndvZmYnKSBmb3JtYXQoJ3dvZmYnKTtcbiAgfVxuICBcbiAgXG4gIEBmb250LWZhY2Uge1xuICBmb250LWZhbWlseTogJ05lbyBTYW5zICBUUiBVbHRyYSc7XG4gIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgZm9udC13ZWlnaHQ6IG5vcm1hbDtcbiAgc3JjOiBsb2NhbCgnZm9udHMvTmVvIFNhbnMgIFRSIFVsdHJhJyksIHVybCgnL2Fzc2V0cy9mb250cy9OZW9TYW5zIFVsdHJhVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG4gIFxuICBcbiAgQGZvbnQtZmFjZSB7XG4gIGZvbnQtZmFtaWx5OiAnTmVvIFNhbnMgIFRSIEJsYWNrIEl0YWxpYyc7XG4gIGZvbnQtc3R5bGU6IG5vcm1hbDtcbiAgZm9udC13ZWlnaHQ6IG5vcm1hbDtcbiAgc3JjOiBsb2NhbCgnZm9udHMvTmVvIFNhbnMgIFRSIEJsYWNrIEl0YWxpYycpLCB1cmwoJy9hc3NldHMvZm9udHMvTmVvU2FucyBCbGFjayBJdGFsaWMgVFIud29mZicpIGZvcm1hdCgnd29mZicpO1xuICB9XG5cblxuXG4gIC8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi9cblxuICAvKiBhanVzdGVzIHBlcXVlbm9zICovXG4gIC5hanVzdGUtdGV4dC1hbGlnbi1yaWdodHtcbiAgICB0ZXh0LWFsaWduOiByaWdodDtcbiAgfVxuICAuYWp1c3RlLXRleHQtYWxpZ24tY2VudGVye1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgfVxuXG4gIC5mb250LXdlaWdodC1ib2xke1xuICAgIGZvbnQtd2VpZ2h0OiBib2xkO1xuICB9XG4gIC5idG4tY2xpZW50ZXtcbiAgICAgIG9wYWNpdHk6IDAuNjtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgICBwYWRkaW5nOiAxcHggMTBweCAhaW1wb3J0YW50OyBcbiAgfVxuXG4gIC5idG4tY2xpZW50ZS1hdGl2b3tcbiAgICBvcGFjaXR5OiAxO1xuICB9XG5cbiAgLmJ0bi1jbGllbnRlOmhvdmVyLFxuICAuYnRuLWNsaWVudGU6Zm9jdXMsXG4gIC5idG4tY2xpZW50ZTphY3RpdmUgeyAgXG4gICAgICBvcGFjaXR5OiAxO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZiAhaW1wb3J0YW50O1xuICAgICAgcGFkZGluZzogMXB4IDEwcHggIWltcG9ydGFudDsgXG4gIH1cblxuICAubGFiZWwtaXRlbnMtdGVsYXtcbiAgICBjb2xvcjogIzY2NjY2NlxuICB9XG5cbiAgLnBhZGRpbmctemVyb3tcbiAgICBwYWRkaW5nOiAwICFpbXBvcnRhbnQ7XG4gIH1cblxuXG4gIC8qYWp1c3RlcyB0YWJlbGEgaW5pY2lvKi9cbiAgLmJvcmRlci10YWJlbGF7XG4gICAgYm9yZGVyOiAycHggc29saWQgI2QzZDNkMztcbiAgfVxuXG4gIC50YWJsZS1zdHJpcGVkPnRib2R5PnRyOm50aC1vZi10eXBlKGV2ZW4pIHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjlmOWY5ICFpbXBvcnRhbnQ7XG59XG5cbi50YWJsZS1zdHJpcGVkPnRib2R5PnRyOm50aC1vZi10eXBlKG9kZCkge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmICFpbXBvcnRhbnQ7XG59XG5cbi5hanVzdGUtdGhlYWR7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlMGUwZTA7XG59XG5cbiAgLnRhYmxlPnRib2R5PnRyPnRkLFxuICAudGFibGU+dGJvZHk+dHI+dGgsXG4gIC50YWJsZT50Zm9vdD50cj50ZCxcbiAgLnRhYmxlPnRmb290PnRyPnRoLFxuICAudGFibGU+dGhlYWQ+dHI+dGQsXG4gIC50YWJsZT50aGVhZD50cj50aHtcbiAgICBib3JkZXItdG9wOiBub25lO1xuICB9XG5cbiAgLnRvdGFsLXByZcOnb3tcbiAgICBmbG9hdDogcmlnaHQ7XG4gICAgZm9udC13ZWlnaHQ6IGJvbGQ7XG4gICAgbWFyZ2luOiA1cHggMCAzMHB4IDA7XG4gIH1cbiAgLnRvdGFsLXByZcOnby1jb3J7XG4gICAgY29sb3I6ICM1YjJmOTA7XG4gIH1cblxuICAubGlua3MtdGFiZWxhe1xuICAgIGNvbG9yOiAjNWIyZjkwO1xuICAgIHRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lO1xuICB9XG5cbiAgLmJ0bi1hdHVhbGl6YXJ7XG4gICAgbWFyZ2luOiA0cHggMCAwIDAgIWltcG9ydGFudDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmICFpbXBvcnRhbnQ7XG4gIH1cblxuIC8qYWp1c3RlcyB0YWJlbGEgZmltKi9cblxuXG5cblxuLyphanVzdGVzIGV0YXBhcyBpbmljaW8qL1xuICAuaW5saW5lLWJsb2Nre2Rpc3BsYXk6IGlubGluZS1ibG9jazt9XG4gIC5wYWRkaW5nLWxlZnR7cGFkZGluZzogMCAwIDAgMjBweDt9XG4gIC5wYWRkaW5nLXJpZ2h0e3BhZGRpbmc6IDAgMjBweCAwIDA7fVxuICAucGFkZGluZy1sZWZ0LXJpZ2h0e3BhZGRpbmc6IDAgMjBweCAwIDIwcHg7fVxuICBcbiAgLmFqdXN0ZS1jZXN0YS1kZS1wcm9kdXRvc3tcbiAgICBtYXJnaW4tYm90dG9tOiAzMHB4O1xuICB9XG5cbiAgLypjZXN0YSBkZSBwcm9kdXRvcyovXG4gIC5jZXN0YS1kZS1wcm9kdXRvcy1mb3Jtc3tcbiAgICBtYXgtd2lkdGg6IDE2MHB4O1xuICAgIGZvbnQtc2l6ZTogMTNweDtcbiAgICBtYXJnaW4tcmlnaHQ6IDdweDtcbiAgfSBcblxuICAuY2VzdGEtZGUtcHJvZHV0b3MtZm9ybXMye1xuICAgIG1heC13aWR0aDogMjYwcHg7XG4gICAgZm9udC1zaXplOiAxM3B4O1xuICAgIG1hcmdpbi1yaWdodDogN3B4O1xuICB9IFxuXG5cbiAgLmFqdXN0ZS10ZXh0LWFsaWduLWNlbnRlcntcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cblxuICAuYWp1c3RlLWJhcnJhLWV0YXBhLXNwYW57XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmN2Y4Zjg7XG4gICAgY29sb3I6ICM3YzdjN2M7XG4gIH1cblxuICAuYWp1c3RlLWJhcnJhLWV0YXBhLXNwYW4tc2VsZWN0ZWR7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2Y3ZjhmODtcbiAgICBjb2xvcjogIzQyMWM1YTtcbiAgfVxuXG4gIC5hanVzdGUtYmFycmEtZXRhcGFze1xuICAgIGJhY2tncm91bmQ6ICNjNGM0YzQ7XG4gICAgaGVpZ2h0OiAycHg7XG4gICAgdG9wOiAtMTBweDtcbiAgfVxuXG4gIC5hanVzdGUtYmFycmEtaXRlbnN7XG4gICAgei1pbmRleDogMTA7XG4gIH0gXG5cbiAgLmV0YXBhcy1udW1lcm9ze1xuICAgIGJvcmRlcjogMXB4IHNvbGlkIGdyZXk7XG4gICAgYm9yZGVyLXJhZGl1czogNTBweDtcbiAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIHBhZGRpbmc6IDBweCA2cHg7XG4gICAgY29sb3I6ICM3YzdjN2M7XG59XG5cbi5ldGFwYXMtbnVtZXJvcy1zZWxlY3RlZHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzQyMWM1YTtcbiAgYm9yZGVyOiAxcHggc29saWQgIzQyMWM1YTtcbiAgYm9yZGVyLXJhZGl1czogNTBweDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIHBhZGRpbmc6IDBweCA2cHg7XG4gIGNvbG9yOiAjZmZmO1xufVxuXG5cbi8qYWp1c3RlcyBldGFwYXMgZmltKi9cblxuICBcbiAgXG4uYnRuLXNldGEtbGVmdHtcbiAgbGVmdDo2MHB4O1xufVxuLmJ0bi1zZXRhLXJpZ2h0e1xuICBsZWZ0OiAwO1xufVxuXG4vKiBmb3JtICovXG4uZm9ybS1jb250cm9se1xuICB3aWR0aDogMTAwJSAhaW1wb3J0YW50O1xuICBoZWlnaHQ6IDM1cHg7XG4gIGJvcmRlci1yYWRpdXM6IDJweDtcbiAgXG5cbn1cblxuLypmb3JtIGNsaWVudGUgZSB0aXBvIGRlIHBlZGlkbyovXG4uY2xpZW50ZS10aXBve1xuICBmbG9hdDogcmlnaHQ7XG59XG5cblxuLyppbnB1dCBpbmljaW8qL1xuLmV4ZW1wbG8xIGlucHV0W3R5cGU9cmFkaW9dLCAuZXhlbXBsbzEgaW5wdXRbdHlwZT1jaGVja2JveF0sIC5leGVtcGxvMiBpbnB1dFt0eXBlPWNoZWNrYm94XXtcbiAgZGlzcGxheTpub25lOyAvKiBFc2NvbmRlIG9zIGlucHV0cyAqL1xufVxuXG4vKmFqdXN0ZSBuYSB0YWJlbGEqL1xuLmFqdXN0ZS1jaGVja2JveDF7XG4gIHRvcDogMTVweDtcbiAgcG9zaXRpb246IGFic29sdXRlO1xufVxuXG4vKlF1ZXJpZXMgdGFtYW5obyovXG5AbWVkaWEgKG1heC13aWR0aDogMTI4OXB4KSB7XG4gIC5hanVzdGUtY2hlY2tib3gxeyBcbiAgIHBvc2l0aW9uOnJlbGF0aXZlIWltcG9ydGFudDtcbiAgIHRvcDogMTBweDtcbiAgIGJvcmRlcjogbm9uZTtcbiAgIH1cbiAgXG4gfVxuXG5AbWVkaWEgKG1heC13aWR0aDogODk5cHgpIHtcbiAuYWp1c3RlLWNoZWNrYm94MXsgXG4gIHBvc2l0aW9uOnJlbGF0aXZlIWltcG9ydGFudDtcbiAgdG9wOiA2cHg7XG4gIGJvcmRlcjogbm9uZTtcbiAgfVxuIFxufVxuQG1lZGlhIChtYXgtd2lkdGg6IDg5OXB4KSB7XG4gIC5hanVzdGUtY2hlY2tib3gxeyBcbiAgIHBvc2l0aW9uOnJlbGF0aXZlIWltcG9ydGFudDtcbiAgIHRvcDogNnB4O1xuICAgYm9yZGVyOiBub25lO1xuICAgfVxuICBcbiB9XG4gXG5cblxuLmV4ZW1wbG8ye1xuICB0b3A6IDEwcHg7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbn1cbi5hanVzdGUtcm93LWNoZWNrYm94e1xuICB3aWR0aDogMzZweDtcbn1cblxuXG5cbi5leGVtcGxvMSBpbnB1dFt0eXBlPXJhZGlvXSArIGxhYmVsLFxuLmV4ZW1wbG8xIGlucHV0W3R5cGU9Y2hlY2tib3hdICsgbGFiZWwsXG4uZXhlbXBsbzIgaW5wdXRbdHlwZT1jaGVja2JveF0gKyBsYWJlbHtcbiAgZGlzcGxheTppbmxpbmUtYmxvY2s7XG4gIGhlaWdodDoyMHB4O1xuICBwYWRkaW5nOjAgMCAwIDI1cHg7XG4gIG1hcmdpbjowIDEwcHggMCAwO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoL2Fzc2V0cy9pbWFnZXMvaWNvLW1hc3Rlci5wbmcpO1xuICBiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7XG4gIGJhY2tncm91bmQtcG9zaXRpb246MCAwO1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gIGZvbnQtc2l6ZTogMTNweDtcbiAgY29sb3I6ICM2NjY2NjY7XG4gIGxpbmUtaGVpZ2h0OiAyMXB4O1xufVxuXG5cbi5leGVtcGxvMSBpbnB1dFt0eXBlPWNoZWNrYm94XSArIGxhYmVsLFxuLmV4ZW1wbG8yIGlucHV0W3R5cGU9Y2hlY2tib3hdICsgbGFiZWx7XG4gIGJhY2tncm91bmQtcG9zaXRpb246MCAtNjBweDsgLyogTXVkYSBhIHBvc2nDp8OjbyBkbyBiYWNrZ3JvdW5kIHPDsyBubyBjaGVja2JveCAqL1xufVxuXG4uZXhlbXBsbzEgaW5wdXRbdHlwZT1jaGVja2JveF06Y2hlY2tlZCArIGxhYmVsIHtcbiAgYmFja2dyb3VuZC1wb3NpdGlvbjowIC05MHB4O1xufVxuXG4uZXhlbXBsbzIgaW5wdXRbdHlwZT1jaGVja2JveF06Y2hlY2tlZCArIGxhYmVsIHtcbiAgYmFja2dyb3VuZC1wb3NpdGlvbjowIC05MHB4O1xufVxuXG4uZXhlbXBsbzIgaW5wdXRbdHlwZT1jaGVja2JveF06Y2hlY2tlZCArIGxhYmVsIHtcbiAgYmFja2dyb3VuZC1wb3NpdGlvbjowIC0xMTlweDsgLyogc2luYWwgZGUgbWVub3MgKi9cbn1cblxuLmV4ZW1wbG8xIGlucHV0W3R5cGU9cmFkaW9dOmNoZWNrZWQgKyBsYWJlbHtcbiAgYmFja2dyb3VuZC1wb3NpdGlvbjowIC0zMHB4O1xufVxuXG4vKmFqdXN0ZSBuYSB0YWJlbGEqL1xuLmV4ZW1wbG8xLCAuZXhlbXBsbzJ7XG4gIFxufVxuXG5cbi8qaW5wdXQgZmltKi9cblxuXG4vKiBHTE9CQUxcbi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0qL1xuXG5oMntcbiAgZm9udC1zaXplOiAxOHB4O1xuICAvKmZvbnQtZmFtaWx5OiBOZW8gU2FucyBUUiBSZWd1bGFyOyovXG4gIG1hcmdpbi1ib3R0b206IDIycHg7XG4gIGNvbG9yOiAjNGU0ZTRlO1xufVxuXG4ubmF2LWxhYmVse1xuICBmb250LWZhbWlseTpOZW8gU2FucyBUUiBSZWd1bGFyO1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gIHdpZHRoOiAxMTJweDtcbiAgZm9udC1zaXplOiAxM3B4O1xuICBtYXJnaW4tbGVmdDogOHB4O1xufVxuXG4ubWVudS1wZWRpZG8tZGUtdmVuZGF7cGFkZGluZzogMCAhaW1wb3J0YW50O31cbi5tZW51LXBlZGlkby1kZS12ZW5kYSAubmF2LWxhYmVse21hcmdpbi1sZWZ0OiA0OXB4OyB9XG4ubWVudS1wZWRpZG8tZGUtdmVuZGEtZGlzcGxheXtcbiAgZGlzcGxheTogbm9uZSAhaW1wb3J0YW50O1xufVxuXG5cbi5uYXZiYXItZ2xvYmFsIHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiBpbmRpZ287XG4gIH1cbiAgXG4gIC5uYXZiYXItZ2xvYmFsIC5uYXZiYXItYnJhbmQge1xuICAgIGNvbG9yOiB3aGl0ZTtcbiAgfVxuICBcbiAgLm5hdmJhci1nbG9iYWwgLm5hdmJhci11c2VyID4gbGkgPiBhXG4gIHtcbiAgICBjb2xvcjogd2hpdGU7XG4gIH1cbiAgXG4gIC5uYXZiYXItcHJpbWFyeSB7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjtcbiAgICBib3R0b206IDBweDtcbiAgICBsZWZ0OiAwcHg7XG4gICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgIC8qdG9wOiA1MXB4OyovXG4gICAgdG9wOiAwO1xuICAgIHdpZHRoOiAyMDBweDtcbiAgICBoZWlnaHQ6IG1heC1jb250ZW50O1xuICAgIHotaW5kZXg6IDg7XG4gICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAtd2Via2l0LXRyYW5zaXRpb246IGFsbCAwLjFzIGVhc2UtaW4tb3V0O1xuICAgIC1tb3otdHJhbnNpdGlvbjogYWxsIDAuMXMgZWFzZS1pbi1vdXQ7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMXMgZWFzZS1pbi1vdXQ7XG4gICAgLyotd2Via2l0LWJveC1zaGFkb3c6IDJweCAycHggN3B4IDBweCByZ2JhKDIyMiwyMjIsMjIyLDAuMjUpO1xuICAgIC1tb3otYm94LXNoYWRvdzogMnB4IDJweCA3cHggMHB4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7XG4gICAgYm94LXNoYWRvdzogMnB4IDJweCA3cHggMHB4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7Ki9cbiAgfVxuICBcbiAgLm5hdmJhci1wcmltYXJ5LmNvbGxhcHNlZCB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICB9XG4gIFxuICAubmF2YmFyLXByaW1hcnkuY29sbGFwc2VkIC5nbHlwaGljb24ge1xuICAgIGZvbnQtc2l6ZTogMTdweDtcbiAgfVxuICBcbiAgLm5hdmJhci1wcmltYXJ5LmNvbGxhcHNlZCAubmF2LWxhYmVsIHtcbiAgICBkaXNwbGF5OiBub25lO1xuICB9XG4gIFxuICAuYnRuLWV4cGFuZC1jb2xsYXBzZSB7XG4gICAgICBvdXRsaW5lOiBub25lO1xuICAgICAgbWFyZ2luLWJvdHRvbTogMjlweDtcbiAgICAgIC8qcG9zaXRpb246IGFic29sdXRlOyovXG4gICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgIGxlZnQ6IDBweDtcbiAgICAgIGJvdHRvbTowO1xuICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICBwYWRkaW5nOiAyMXB4IDA7XG4gICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2RiZGJkYjsgIFxuICAgICAgLypib3JkZXItdG9wOnNvbGlkIDFweCAjNjY2OyovXG4gICAgICBjb2xvcjogI2NjYztcbiAgICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAgIGJvcmRlci10b3A6IDA7XG4gICAgICBib3JkZXItbGVmdDogMDtcbiAgICAgIGJvcmRlci1yaWdodDogMDtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgICB3ZWJraXQtYm94LXNoYWRvdzogMHB4IDBweCAwcHggMXB4IHJnYmEoMCwwLDAsMC4wNSk7XG4gICAgLW1vei1ib3gtc2hhZG93OiAwcHggMHB4IDBweCAxcHggcmdiYSgwLDAsMCwwLjA1KTtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAxcHggcmdiYSgwLDAsMCwwLjA1KTtcbiAgfVxuICBcbiAgLmJ0bi1leHBhbmQtY29sbGFwc2U6aG92ZXIsXG4gIC5idG4tZXhwYW5kLWNvbGxhcHNlOmZvY3VzIHtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgICBjb2xvcjogI2NjYztcbiAgfVxuICBcbiAgLmJ0bi1leHBhbmQtY29sbGFwc2U6YWN0aXZlIHtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gIH1cbiAgXG4gIC5uYXZiYXItcHJpbWFyeS1tZW51LFxuICAubmF2YmFyLXByaW1hcnktbWVudSBsaSB7XG4gICAgbWFyZ2luOjA7IHBhZGRpbmc6MDtcbiAgICBsaXN0LXN0eWxlOiBub25lO1xuICB9XG4gIFxuXG5cbiAgLm5hdmJhci1wcmltYXJ5LW1lbnUgbGkgYSB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gICAgcGFkZGluZzogMTBweCAxOHB4O1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gICAgLypib3JkZXItYm90dG9tOnNvbGlkIDFweCAjNDQ0OyovXG4gICAgY29sb3I6ICM5NDk3OWI7XG4gIH1cbiAgXG4gIC5uYXZiYXItcHJpbWFyeS1tZW51IGxpIGE6aG92ZXIge1xuICAgIGNvbG9yOiAjNWMyZTkwO1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICB9XG5cbiAgLm5hdmJhci1wcmltYXJ5LW1lbnUgbGkgYTphY3RpdmUsXG4gIC5uYXZiYXItcHJpbWFyeS1tZW51IGxpIGE6Zm9jdXN7XG4gICAgY29sb3I6ICM1YzJlOTA7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICB9XG4gIFxuICAubmF2YmFyLXByaW1hcnktbWVudSBsaSBhIC5nbHlwaGljb24ge1xuICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICBjb2xvcjogIzk0OTc5YjtcbiAgICBtYXJnaW4tcmlnaHQ6IDZweDtcbiAgICBmb250LXNpemU6IDE3cHg7XG4gIH1cblxuICAuYWp1c3RlLW5hdmJhci1wcmltYXJ5LWljb25ze1xuICAgIHRvcDogLTZweDtcbiAgfVxuICBcbiAgLm5hdmJhci1wcmltYXJ5LW1lbnUgbGkgYTpob3ZlciAuZ2x5cGhpY29uIHtcbiAgICBjb2xvcjogIzVjMmU5MDtcbiAgfVxuICAubmF2YmFyLXByaW1hcnktbWVudSBsaSBhOmZvY3VzIC5nbHlwaGljb24ge1xuICAgIGNvbG9yOiAjNWMyZTkwO1xuICB9XG4gIFxuICAubWFpbi1jb250ZW50IHtcbiAgICBvdmVyZmxvdy14OiBoaWRkZW47XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2Y3ZjhmODtcbiAgICAvKm1hcmdpbi10b3A6IDYwcHg7Ki9cbiAgICBtYXJnaW4tbGVmdDogMjAwcHg7XG4gICAgcGFkZGluZzogMCAwIDkwcHggMDtcbiAgICAtd2Via2l0LWJveC1zaGFkb3c6IGluc2V0IDEwcHggMHB4IDdweCAtN3B4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7XG4gICAgLW1vei1ib3gtc2hhZG93OiBpbnNldCAxMHB4IDBweCA3cHggLTdweCByZ2JhKDIyMiwyMjIsMjIyLDAuMjUpO1xuICAgIGJveC1zaGFkb3c6IGluc2V0IDEwcHggMHB4IDdweCAtN3B4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7XG4gIH1cblxuICAubWFpbi1jb250ZW50MntcbiAgICBvdmVyZmxvdy14OiBoaWRkZW47XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2Y3ZjhmODtcbiAgICAvKm1hcmdpbi10b3A6IDYwcHg7Ki9cbiAgICBtYXJnaW4tbGVmdDogMTAwcHg7XG4gICAgcGFkZGluZzogMCAwIDkwcHggMDtcbiAgICAtd2Via2l0LWJveC1zaGFkb3c6IGluc2V0IDEwcHggMHB4IDdweCAtN3B4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7XG4gICAgLW1vei1ib3gtc2hhZG93OiBpbnNldCAxMHB4IDBweCA3cHggLTdweCByZ2JhKDIyMiwyMjIsMjIyLDAuMjUpO1xuICAgIGJveC1zaGFkb3c6IGluc2V0IDEwcHggMHB4IDdweCAtN3B4IHJnYmEoMjIyLDIyMiwyMjIsMC4yNSk7XG4gICB9XG5cblxuICAubWFpbi1jb250ZW50IGgxe1xuICAgIGZvbnQtc2l6ZTogMThweDtcbiAgICBtYXJnaW46IDA7XG4gICAgcGFkZGluZzogMjdweCAwIDI0cHggMzBweDtcbiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2RiZGJkYjtcbiAgfVxuXG4gIFxuXG4gIFxuICAuY29sbGFwc2VkICsgLm1haW4tY29udGVudCB7XG4gICAgbWFyZ2luLWxlZnQ6IDEwMHB4O1xuICAgIHBhZGRpbmc6IDAgMCA2MHB4IDA7XG4gIH1cblxuICAuY29sbGFwc2VkIC5uYXZiYXItcHJpbWFyeS1tZW51IGxpIGEge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgfVxuXG4gIC5jb2xsYXBzZWQgLmxvZ28ge2Rpc3BsYXk6bm9uZTt9XG5cblxuICAubG9nbyB7XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICBsZWZ0OiAyMnB4O1xuICAgIHRvcDogMTZweDtcbiAgfVxuXG4gIC8qYm90b2VzLWluaWNpYWlzKi9cbiAgLmJvdG9lcy1pbmljaWFpc3tcbiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2RiZGJkYjtcbiAgICBwYWRkaW5nOiAwIDMwcHg7XG4gIH1cblxuICAuYnRuLWluaWNpb3tcbiAgICBtYXJnaW46IDEwcHggMCAxMHB4IDA7XG4gICAgYm9yZGVyLXJhZGl1czogMnB4O1xuICAgIGZvbnQtc2l6ZTogMTNweDtcbiAgICBmb250LXdlaWdodDogYm9sZDtcbiAgfVxuXG4gIC5idG4tdG9wby1kaXJlaXRhe1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmN2Y4Zjg7XG4gICAgY29sb3I6ICM2NjY7XG4gIH1cblxuICAuYnRuLXRvcG8tZGlyZWl0YTpob3ZlcixcbiAgLmJ0bi10b3BvLWRpcmVpdGE6YWN0aXZlLFxuICAuYnRuLXRvcG8tZGlyZWl0YTpmb2N1c1xuXG4gIHtcbiAgICBjb2xvcjogI2ZmZiAhaW1wb3J0YW50O1xuICAgIGJhY2tncm91bmQtY29sb3I6ICM0MjFiNWIgIWltcG9ydGFudDtcbiAgICBib3JkZXItY29sb3I6ICM0MjFiNWIgIWltcG9ydGFudDtcbiAgfVxuICBcbiAgLmJ0bi1wcm94aW1ve1xuICAgIGJhY2tncm91bmQtY29sb3I6ICM0MjFiNWI7XG4gICAgY29sb3I6ICNmZmY7XG4gICAgYm9yZGVyOiAxcHggc29saWQgIzQyMWI1YjtcbiAgICBtYXJnaW4tbGVmdDogMTBweDtcbiAgfVxuXG4gIC5idG4tcHJveGltbzpob3ZlcixcbiAgLmJ0bi1wcm94aW1vOmFjdGl2ZSxcbiAgLmJ0bi1wcm94aW1vOmZvY3Vze1xuICAgIGNvbG9yOiAjZmZmICFpbXBvcnRhbnQ7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogIzM0MTg1NyAhaW1wb3J0YW50O1xuICAgIGJvcmRlcjogMXB4IHNvbGlkICMzNDE4NTcgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5idG4tcGF1c2V7XG4gICAgYm9yZGVyOiAxcHggc29saWQgIzQyMWI1YjtcbiAgICBjb2xvcjogIzQyMWI1YjtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjdmOGY4O1xuICAgIG1hcmdpbi1yaWdodDogMTBweDtcbiAgfVxuXG4gIC5idG4tcGF1c2U6aG92ZXIsXG4gIC5idG4tcGF1c2U6YWN0aXZlLFxuICAuYnRuLXBhdXNlOmZvY3Vze1xuICAgIGNvbG9yOiAjZmZmICFpbXBvcnRhbnQ7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogIzQyMWI1YiAhaW1wb3J0YW50O1xuICAgIGJvcmRlcjogMXB4IHNvbGlkICM0MjFiNWIgIWltcG9ydGFudDtcbiAgfVxuXG5cbiAgLmJsb2NrLWJyYW5jby1hanVzdGUtYWx0dXJhMXtcbiAgICBtYXJnaW46IDI4cHggMjhweCAwIDI4cHggIWltcG9ydGFudDtcbiAgfVxuXG4gIC5ibG9jay1icmFuY28tYWp1c3RlLWFsdHVyYTJ7XG4gICAgbWFyZ2luOiAwIDI4cHggMjhweCAyOHB4ICAhaW1wb3J0YW50O1xuICB9XG4gIFxuXG5cbiAgLmJsb2NrLWJyYW5jb3tcbiAgICBtYXJnaW46IDI4cHggMjhweDtcbiAgICBwYWRkaW5nOiAwIDEwcHggMCAxMHB4O1xuICAgIGJhY2tncm91bmQ6ICNmZmY7XG4gICAgYm9yZGVyLXJhZGl1czogNHB4O1xuICAgIC13ZWJraXQtYm94LXNoYWRvdzogMHB4IDBweCAycHggMXB4IHJnYmEoMCwwLDAsMC4wOSk7XG4gICAtbW96LWJveC1zaGFkb3c6IDBweCAwcHggMnB4IDFweCByZ2JhKDAsMCwwLDAuMDkpO1xuICAgYm94LXNoYWRvdzogMHB4IDBweCAycHggMXB4IHJnYmEoMCwwLDAsMC4wOSk7XG4gIH1cblxuICAuYmxvY2stYnJhbmNvLXNlYXJjaHtcbiAgICBwYWRkaW5nOiAyMHB4IDIwcHggMjBweCAxNXB4O1xuICAgIGJhY2tncm91bmQ6ICNmZmY7XG4gICAgYm9yZGVyLXJhZGl1czogMXB4O1xuICAgIC13ZWJraXQtYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICAgIC1tb3otYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICAgIGJveC1zaGFkb3c6IDEwcHggMTBweCAxOXB4IC0xMnB4IHJnYmEoMCwwLDAsMC42KTtcbiAgICBib3JkZXI6IDFweCBzb2xpZCAjY2NjO1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICB6LWluZGV4OiA5OTk5OTtcbiAgICB3aWR0aDogOTclO1xuICAgIGxlZnQ6IDMxcHg7XG4gICAgdG9wOiAzNHB4O1xuICB9XG5cbiAgXG4gIC5ibG9jay1icmFuY28tZmx5bWVudXtcbiAgICBwYWRkaW5nOiAyMHB4IDE4cHggMjBweCAxMnB4O1xuICAgIGJhY2tncm91bmQ6ICNmZmY7XG4gICAgYm9yZGVyLXJhZGl1czogMXB4O1xuICAgIC13ZWJraXQtYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICAgIC1tb3otYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICAgIGJveC1zaGFkb3c6IDEwcHggMTBweCAxOXB4IC0xMnB4IHJnYmEoMCwwLDAsMC42KTtcbiAgICBib3JkZXI6IDFweCBzb2xpZCAjY2NjO1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICB6LWluZGV4OiA5OTk5OTtcbiAgICB3aWR0aDogOTclO1xuICAgIGxlZnQ6IDMxcHg7XG4gICAgdG9wOiAzNHB4O1xuICB9XG5cblxuICAuYmxvY28tbm9ybWFse1xuICAgIG1hcmdpbjogMjhweCAyOHB4O1xuICB9XG5cbiAgLmJsb2NrLWNpbnphe1xuICAgIHBhZGRpbmc6IDIxcHggMThweCA1cHggOHB4O1xuICAgIGJhY2tncm91bmQ6ICNmNGY0ZjQ7XG4gICAgYm9yZGVyLXJhZGl1czogNHB4O1xuICAgIGJvcmRlci1yaWdodDogNDBweCBzb2xpZCAjZTBlMGUwO1xuICAgIG1hcmdpbjogMHB4IDBweCAyMnB4IDA7XG4gICAgLXdlYmtpdC1ib3gtc2hhZG93OiAycHggMnB4IDBweCAwcHggcmdiYSgyMjIsMjIyLDIyMiwxKTtcbiAgICAtbW96LWJveC1zaGFkb3c6IDJweCAycHggMHB4IDBweCByZ2JhKDIyMiwyMjIsMjIyLDEpO1xuICAgIGJveC1zaGFkb3c6IDJweCAycHggMHB4IDBweCByZ2JhKDIyMiwyMjIsMjIyLDEpO1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgfVxuXG4gIC5ibG9jay1jaW56YS1zZWFyY2h7XG4gICAgcGFkZGluZzogMjBweCAxOHB4IDIwcHggNXB4O1xuICAgIGJhY2tncm91bmQ6ICNmNGY0ZjQ7XG4gICAgYm9yZGVyLXJhZGl1czogNnB4O1xuICAgIG1hcmdpbjogMCAwIDIwcHggNHB4O1xuICAgIGJvcmRlcjogMXB4IHNvbGlkIHJnYigyMjQsIDIyNCwgMjI0KTtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gIH1cblxuICAuc2VhcmNoLXByb2R1dG8tdGV4dHtcbiAgICBjb2xvcjogIzdjN2M3YztcbiAgfVxuXG4gIC5zZWFyY2gtaW1hZ2V7ICAgIFxuICAgIGJvcmRlci1yYWRpdXM6IDRweDtcbiAgICBib3JkZXI6IDFweCBzb2xpZCAjYzJjMmMyO1xuICAgIG1pbi13aWR0aDogOTBweDtcbiAgfVxuXG4gIC5idG4tcHJvZHV0by1hZGljaW9uYXJ7XG4gICAgYm9yZGVyOiAxcHggc29saWQgIzViMmY5MDtcbiAgICBjb2xvcjogIzViMmY5MDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjRmNGY0O1xuICB9XG4gIC5idG4tcHJvZHV0by1hZGljaW9uYXI6aG92ZXIsIC5idG4tcHJvZHV0by1hZGljaW9uYXI6YWN0aXZlLCAuYnRuLXByb2R1dG8tYWRpY2lvbmFybi1wYXVzZTpmb2N1cyB7XG4gICAgY29sb3I6ICNmZmYgIWltcG9ydGFudDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjNDcxZjc5ICFpbXBvcnRhbnQ7XG4gICAgYm9yZGVyOiAxcHggc29saWQgIzQ3MWY3OSAhaW1wb3J0YW50O1xufVxuXG4gIC5idG4tdmVyLXR1ZG8tc2VhcmNoe1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAvKiBkaXNwbGF5OiBibG9jazsgKi9cbiAgICAvKiB3aWR0aDogMTQlOyAqL1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gIH1cblxuLmNhbXBvLWJ1c2Nhe1xuICBcbn1cblxuLmljb25lLWNhbXBvLWJ1c2Nhe1xuICAgIGJhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybCgvYXNzZXRzL2ltYWdlcy9pY28tbWFzdGVyLnBuZyk7XG4gICAgYmFja2dyb3VuZC1wb3NpdGlvbjogMCAtMTM5cHg7XG4gICAgZmxvYXQ6IHJpZ2h0O1xuICAgIHdpZHRoOiAzMHB4O1xuICAgIGhlaWdodDogMzBweDtcbiAgICBtYXJnaW46IC0zMnB4IDAgMCAwO1xufVxuXG4udGFibGUtZm9ybS1xdWFudGlkYWRle1xuICBwYWRkaW5nOiA2cHggNXB4ICFpbXBvcnRhbnQ7XG4gIG1heC13aWR0aDogMzNweDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xufVxuXG4vKmRlc2NvbWVudGFyKi9cbi5zZWFyY2hfYm94e1xuICBkaXNwbGF5Om5vbmU7XG59XG4uYWRpY2lvbmFyLWp1bnRve1xuICBkaXNwbGF5Om5vbmU7XG59XG5cbi5hY3RpdmUtc2VhcmNoe1xuICBkaXNwbGF5OiBibG9jaztcbn1cbi5hY3RpdmUtYWRpY2lvbmFyLWp1bnRve1xuICBkaXNwbGF5OmJsb2NrICFpbXBvcnRhbnQ7XG59XG5cblxuXG4vKiBEUkFHR0FCTEUgKi9cbiNkcmFnZ2FibGV7XG4gIHBhZGRpbmctdG9wOiAwICFpbXBvcnRhbnQ7XG4gIG1heC13aWR0aDogNTYwcHg7XG4gIG1pbi1oZWlnaHQ6IDE1MHB4O1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHotaW5kZXg6OTk5OTk5O1xuICBib3JkZXItcmFkaXVzOiA2cHg7XG4gIC13ZWJraXQtYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICAtbW96LWJveC1zaGFkb3c6IDEwcHggMTBweCAxOXB4IC0xMnB4IHJnYmEoMCwwLDAsMC42KTtcbiAgYm94LXNoYWRvdzogMTBweCAxMHB4IDE5cHggLTEycHggcmdiYSgwLDAsMCwwLjYpO1xuICBib3JkZXI6IDFweCBzb2xpZCAjYWRhZGFkO1xufVxuXG4uYWRpY2lvbmFyLWp1bnRvLXRpdGxle1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjNDIxYjViO1xuICAgIG1hcmdpbi1ib3R0b206IDIwcHg7XG4gICAgY29sb3I6ICNmZmY7XG4gICAgcGFkZGluZzogMjBweCAyMHB4O1xuICAgIGZvbnQtc2l6ZTogMThweDtcbiAgICB0b3A6IC0xcHg7XG4gICAgbGVmdDogM3B4O1xuICAgIGJvcmRlci10b3AtbGVmdC1yYWRpdXM6IDZweDtcbiAgICBib3JkZXItdG9wLXJpZ2h0LXJhZGl1czogNnB4O1xuICAgIG1heC13aWR0aDogNTYwcHg7XG59XG5cblxuLyogU0NST0xMIEJBUiBDU1MqL1xuXG46Oi13ZWJraXQtc2Nyb2xsYmFyLXRyYWNrIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogcmdiKDE0NSwgMTQ1LCAxNDUpO1xufVxuOjotd2Via2l0LXNjcm9sbGJhciB7XG4gIHdpZHRoOiAxMnB4O1xuICBiYWNrZ3JvdW5kOiByZ2IoNTgsIDU4LCA1OCk7XG59XG46Oi13ZWJraXQtc2Nyb2xsYmFyLXRodW1iIHtcbiAgYmFja2dyb3VuZDogIzVjNWM1YztcbiAgLypib3JkZXItcmFkaXVzOiA4cHg7Ki9cbn1cblxuLypjc3MgdGFiZWxhKi9cbi50YWJsZT50Ym9keT50cj50ZCxcbi50YWJsZT50Ym9keT50cj50aCxcbi50YWJsZT50Zm9vdD50cj50ZCxcbi50YWJsZT50Zm9vdD50cj50aCxcbi50YWJsZT50aGVhZD50cj50ZCxcbi50YWJsZT50aGVhZD50cj50aHtcbiAgICAgIHBhZGRpbmc6IDhweCAxMHB4O1xuICAgICAgbGluZS1oZWlnaHQ6IDEuNDI4NTcxNDM7XG4gICAgICB2ZXJ0aWNhbC1hbGlnbjogaW5pdGlhbDtcbiAgICAgIC8qYm9yZGVyLXRvcDogMXB4IHNvbGlkICNkZGQ7Ki9cbiAgICAgIGZvbnQtc2l6ZTogMTJweDtcbiAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbn1cblxuLnRhYmxlPnRoZWFkOmZpcnN0LWNoaWxkPnRyOmZpcnN0LWNoaWxkPnRoe1xuICBwYWRkaW5nOiAxMnB4IDEwcHg7XG59XG5cbi5idG4tbWFpc3tcbiAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoL2Fzc2V0cy9pbWFnZXMvaWNvLW1hc3Rlci5wbmcpO1xuICBiYWNrZ3JvdW5kLXBvc2l0aW9uOiAwIC0xOTJweDtcbiAgd2lkdGg6IDE5cHg7XG4gIGhlaWdodDogMjJweDtcbn1cblxuLmJ0bi1tZW5vc3tcbiAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoL2Fzc2V0cy9pbWFnZXMvaWNvLW1hc3Rlci5wbmcpO1xuICBiYWNrZ3JvdW5kLXBvc2l0aW9uOiAwIC0xNzBweDtcbiAgd2lkdGg6IDE5cHg7XG4gIGhlaWdodDogMjJweDtcbn1cblxuLypRdWVyaWVzIHRhbWFuaG8qL1xuQG1lZGlhIChtYXgtd2lkdGg6IDk5MXB4KSB7XG4gIC5hanVzdGUtYmFycmEtZXRhcGFze2Rpc3BsYXk6IG5vbmU7fVxuICAuYWp1c3RlLWJhcnJhLWl0ZW5ze3RleHQtYWxpZ246IGxlZnQ7fVxuICAuYWp1c3RlLWJhcnJhLWV0YXBhLXNwYW57cGFkZGluZzogMTBweCAwIDEwcHggMCAhaW1wb3J0YW50O31cbiAgLmFqdXN0ZS1tb2JpbGUtZXNxdWVyZGF7dGV4dC1hbGlnbjpsZWZ0O31cbn1cblxuQG1lZGlhIChtYXgtd2lkdGg6IDgwOHB4KSB7XG4gIC5pY29uZS1jYW1wby1idXNjYXtiYWNrZ3JvdW5kLWltYWdlOiBub25lO31cbn0iXX0= */", '', '']]

/***/ }),

/***/ "./node_modules/style-loader/lib/addStyles.js":
/*!****************************************************!*\
  !*** ./node_modules/style-loader/lib/addStyles.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

var stylesInDom = {};

var	memoize = function (fn) {
	var memo;

	return function () {
		if (typeof memo === "undefined") memo = fn.apply(this, arguments);
		return memo;
	};
};

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

var getTarget = function (target, parent) {
  if (parent){
    return parent.querySelector(target);
  }
  return document.querySelector(target);
};

var getElement = (function (fn) {
	var memo = {};

	return function(target, parent) {
                // If passing function in options, then use it for resolve "head" element.
                // Useful for Shadow Root style i.e
                // {
                //   insertInto: function () { return document.querySelector("#foo").shadowRoot }
                // }
                if (typeof target === 'function') {
                        return target();
                }
                if (typeof memo[target] === "undefined") {
			var styleTarget = getTarget.call(this, target, parent);
			// Special case to return head of iframe instead of iframe itself
			if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
				try {
					// This will throw an exception if access to iframe is blocked
					// due to cross-origin restrictions
					styleTarget = styleTarget.contentDocument.head;
				} catch(e) {
					styleTarget = null;
				}
			}
			memo[target] = styleTarget;
		}
		return memo[target]
	};
})();

var singleton = null;
var	singletonCounter = 0;
var	stylesInsertedAtTop = [];

var	fixUrls = __webpack_require__(/*! ./urls */ "./node_modules/style-loader/lib/urls.js");

module.exports = function(list, options) {
	if (typeof DEBUG !== "undefined" && DEBUG) {
		if (typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
	}

	options = options || {};

	options.attrs = typeof options.attrs === "object" ? options.attrs : {};

	// Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
	// tags it will allow on a page
	if (!options.singleton && typeof options.singleton !== "boolean") options.singleton = isOldIE();

	// By default, add <style> tags to the <head> element
        if (!options.insertInto) options.insertInto = "head";

	// By default, add <style> tags to the bottom of the target
	if (!options.insertAt) options.insertAt = "bottom";

	var styles = listToStyles(list, options);

	addStylesToDom(styles, options);

	return function update (newList) {
		var mayRemove = [];

		for (var i = 0; i < styles.length; i++) {
			var item = styles[i];
			var domStyle = stylesInDom[item.id];

			domStyle.refs--;
			mayRemove.push(domStyle);
		}

		if(newList) {
			var newStyles = listToStyles(newList, options);
			addStylesToDom(newStyles, options);
		}

		for (var i = 0; i < mayRemove.length; i++) {
			var domStyle = mayRemove[i];

			if(domStyle.refs === 0) {
				for (var j = 0; j < domStyle.parts.length; j++) domStyle.parts[j]();

				delete stylesInDom[domStyle.id];
			}
		}
	};
};

function addStylesToDom (styles, options) {
	for (var i = 0; i < styles.length; i++) {
		var item = styles[i];
		var domStyle = stylesInDom[item.id];

		if(domStyle) {
			domStyle.refs++;

			for(var j = 0; j < domStyle.parts.length; j++) {
				domStyle.parts[j](item.parts[j]);
			}

			for(; j < item.parts.length; j++) {
				domStyle.parts.push(addStyle(item.parts[j], options));
			}
		} else {
			var parts = [];

			for(var j = 0; j < item.parts.length; j++) {
				parts.push(addStyle(item.parts[j], options));
			}

			stylesInDom[item.id] = {id: item.id, refs: 1, parts: parts};
		}
	}
}

function listToStyles (list, options) {
	var styles = [];
	var newStyles = {};

	for (var i = 0; i < list.length; i++) {
		var item = list[i];
		var id = options.base ? item[0] + options.base : item[0];
		var css = item[1];
		var media = item[2];
		var sourceMap = item[3];
		var part = {css: css, media: media, sourceMap: sourceMap};

		if(!newStyles[id]) styles.push(newStyles[id] = {id: id, parts: [part]});
		else newStyles[id].parts.push(part);
	}

	return styles;
}

function insertStyleElement (options, style) {
	var target = getElement(options.insertInto)

	if (!target) {
		throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");
	}

	var lastStyleElementInsertedAtTop = stylesInsertedAtTop[stylesInsertedAtTop.length - 1];

	if (options.insertAt === "top") {
		if (!lastStyleElementInsertedAtTop) {
			target.insertBefore(style, target.firstChild);
		} else if (lastStyleElementInsertedAtTop.nextSibling) {
			target.insertBefore(style, lastStyleElementInsertedAtTop.nextSibling);
		} else {
			target.appendChild(style);
		}
		stylesInsertedAtTop.push(style);
	} else if (options.insertAt === "bottom") {
		target.appendChild(style);
	} else if (typeof options.insertAt === "object" && options.insertAt.before) {
		var nextSibling = getElement(options.insertAt.before, target);
		target.insertBefore(style, nextSibling);
	} else {
		throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");
	}
}

function removeStyleElement (style) {
	if (style.parentNode === null) return false;
	style.parentNode.removeChild(style);

	var idx = stylesInsertedAtTop.indexOf(style);
	if(idx >= 0) {
		stylesInsertedAtTop.splice(idx, 1);
	}
}

function createStyleElement (options) {
	var style = document.createElement("style");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}

	if(options.attrs.nonce === undefined) {
		var nonce = getNonce();
		if (nonce) {
			options.attrs.nonce = nonce;
		}
	}

	addAttrs(style, options.attrs);
	insertStyleElement(options, style);

	return style;
}

function createLinkElement (options) {
	var link = document.createElement("link");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}
	options.attrs.rel = "stylesheet";

	addAttrs(link, options.attrs);
	insertStyleElement(options, link);

	return link;
}

function addAttrs (el, attrs) {
	Object.keys(attrs).forEach(function (key) {
		el.setAttribute(key, attrs[key]);
	});
}

function getNonce() {
	if (false) {}

	return __webpack_require__.nc;
}

function addStyle (obj, options) {
	var style, update, remove, result;

	// If a transform function was defined, run it on the css
	if (options.transform && obj.css) {
	    result = typeof options.transform === 'function'
		 ? options.transform(obj.css) 
		 : options.transform.default(obj.css);

	    if (result) {
	    	// If transform returns a value, use that instead of the original css.
	    	// This allows running runtime transformations on the css.
	    	obj.css = result;
	    } else {
	    	// If the transform function returns a falsy value, don't add this css.
	    	// This allows conditional loading of css
	    	return function() {
	    		// noop
	    	};
	    }
	}

	if (options.singleton) {
		var styleIndex = singletonCounter++;

		style = singleton || (singleton = createStyleElement(options));

		update = applyToSingletonTag.bind(null, style, styleIndex, false);
		remove = applyToSingletonTag.bind(null, style, styleIndex, true);

	} else if (
		obj.sourceMap &&
		typeof URL === "function" &&
		typeof URL.createObjectURL === "function" &&
		typeof URL.revokeObjectURL === "function" &&
		typeof Blob === "function" &&
		typeof btoa === "function"
	) {
		style = createLinkElement(options);
		update = updateLink.bind(null, style, options);
		remove = function () {
			removeStyleElement(style);

			if(style.href) URL.revokeObjectURL(style.href);
		};
	} else {
		style = createStyleElement(options);
		update = applyToTag.bind(null, style);
		remove = function () {
			removeStyleElement(style);
		};
	}

	update(obj);

	return function updateStyle (newObj) {
		if (newObj) {
			if (
				newObj.css === obj.css &&
				newObj.media === obj.media &&
				newObj.sourceMap === obj.sourceMap
			) {
				return;
			}

			update(obj = newObj);
		} else {
			remove();
		}
	};
}

var replaceText = (function () {
	var textStore = [];

	return function (index, replacement) {
		textStore[index] = replacement;

		return textStore.filter(Boolean).join('\n');
	};
})();

function applyToSingletonTag (style, index, remove, obj) {
	var css = remove ? "" : obj.css;

	if (style.styleSheet) {
		style.styleSheet.cssText = replaceText(index, css);
	} else {
		var cssNode = document.createTextNode(css);
		var childNodes = style.childNodes;

		if (childNodes[index]) style.removeChild(childNodes[index]);

		if (childNodes.length) {
			style.insertBefore(cssNode, childNodes[index]);
		} else {
			style.appendChild(cssNode);
		}
	}
}

function applyToTag (style, obj) {
	var css = obj.css;
	var media = obj.media;

	if(media) {
		style.setAttribute("media", media)
	}

	if(style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		while(style.firstChild) {
			style.removeChild(style.firstChild);
		}

		style.appendChild(document.createTextNode(css));
	}
}

function updateLink (link, options, obj) {
	var css = obj.css;
	var sourceMap = obj.sourceMap;

	/*
		If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled
		and there is no publicPath defined then lets turn convertToAbsoluteUrls
		on by default.  Otherwise default to the convertToAbsoluteUrls option
		directly
	*/
	var autoFixUrls = options.convertToAbsoluteUrls === undefined && sourceMap;

	if (options.convertToAbsoluteUrls || autoFixUrls) {
		css = fixUrls(css);
	}

	if (sourceMap) {
		// http://stackoverflow.com/a/26603875
		css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
	}

	var blob = new Blob([css], { type: "text/css" });

	var oldSrc = link.href;

	link.href = URL.createObjectURL(blob);

	if(oldSrc) URL.revokeObjectURL(oldSrc);
}


/***/ }),

/***/ "./node_modules/style-loader/lib/urls.js":
/*!***********************************************!*\
  !*** ./node_modules/style-loader/lib/urls.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports) {


/**
 * When source maps are enabled, `style-loader` uses a link element with a data-uri to
 * embed the css on the page. This breaks all relative urls because now they are relative to a
 * bundle instead of the current page.
 *
 * One solution is to only use full urls, but that may be impossible.
 *
 * Instead, this function "fixes" the relative urls to be absolute according to the current page location.
 *
 * A rudimentary test suite is located at `test/fixUrls.js` and can be run via the `npm test` command.
 *
 */

module.exports = function (css) {
  // get current location
  var location = typeof window !== "undefined" && window.location;

  if (!location) {
    throw new Error("fixUrls requires window.location");
  }

	// blank or null?
	if (!css || typeof css !== "string") {
	  return css;
  }

  var baseUrl = location.protocol + "//" + location.host;
  var currentDir = baseUrl + location.pathname.replace(/\/[^\/]*$/, "/");

	// convert each url(...)
	/*
	This regular expression is just a way to recursively match brackets within
	a string.

	 /url\s*\(  = Match on the word "url" with any whitespace after it and then a parens
	   (  = Start a capturing group
	     (?:  = Start a non-capturing group
	         [^)(]  = Match anything that isn't a parentheses
	         |  = OR
	         \(  = Match a start parentheses
	             (?:  = Start another non-capturing groups
	                 [^)(]+  = Match anything that isn't a parentheses
	                 |  = OR
	                 \(  = Match a start parentheses
	                     [^)(]*  = Match anything that isn't a parentheses
	                 \)  = Match a end parentheses
	             )  = End Group
              *\) = Match anything and then a close parens
          )  = Close non-capturing group
          *  = Match anything
       )  = Close capturing group
	 \)  = Match a close parens

	 /gi  = Get all matches, not the first.  Be case insensitive.
	 */
	var fixedCss = css.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi, function(fullMatch, origUrl) {
		// strip quotes (if they exist)
		var unquotedOrigUrl = origUrl
			.trim()
			.replace(/^"(.*)"$/, function(o, $1){ return $1; })
			.replace(/^'(.*)'$/, function(o, $1){ return $1; });

		// already a full url? no change
		if (/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/|\s*$)/i.test(unquotedOrigUrl)) {
		  return fullMatch;
		}

		// convert the url to a full url
		var newUrl;

		if (unquotedOrigUrl.indexOf("//") === 0) {
		  	//TODO: should we add protocol?
			newUrl = unquotedOrigUrl;
		} else if (unquotedOrigUrl.indexOf("/") === 0) {
			// path should be relative to the base url
			newUrl = baseUrl + unquotedOrigUrl; // already starts with '/'
		} else {
			// path should be relative to current directory
			newUrl = currentDir + unquotedOrigUrl.replace(/^\.\//, ""); // Strip leading './'
		}

		// send back the fixed url(...)
		return "url(" + JSON.stringify(newUrl) + ")";
	});

	// send back the fixed css
	return fixedCss;
};


/***/ }),

/***/ "./src/styles.css":
/*!************************!*\
  !*** ./src/styles.css ***!
  \************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!../node_modules/postcss-loader/src??embedded!./styles.css */ "./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src/index.js?!./src/styles.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(false) {}

/***/ }),

/***/ 3:
/*!******************************!*\
  !*** multi ./src/styles.css ***!
  \******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! C:\Users\Victor\Desktop\ANGULAR\Telha-Angular\telha-projeto\src\styles.css */"./src/styles.css");


/***/ })

},[[3,"runtime"]]]);
//# sourceMappingURL=styles.js.map